# Generated by Django 2.2.11 on 2020-03-19 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('dollarBalance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('euBalance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('pesoArBalance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency', models.CharField(choices=[('AR$', 'AR$'), ('US$', 'US$'), ('EU$', 'EU$')], max_length=3)),
                ('message', models.CharField(max_length=250)),
                ('receiverAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverAcc', to='bankAccounts.Account')),
                ('senderAcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderAcc', to='bankAccounts.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransactionUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actionType', models.CharField(choices=[('D', 'Deposito'), ('E', 'Extraccion'), ('T', 'Transferencia'), ('C', 'Creacion|Deposito inicial')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('currency', models.CharField(choices=[('AR$', 'AR$'), ('US$', 'US$'), ('EU$', 'EU$')], max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankAccounts.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionLogUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
